source 'https://rubygems.org'
ruby "2.1.1"

gem 'sinatra'
gem 'json'
gem 'sass'
gem 'parse-ruby-client', :github => 'xavdidtheshadow/parse-ruby-client'
gem 'haml'
gem 'sinatra-flash'
gem 'mail'
gem 'rack-google-analytics'
gem 'mongo'
gem 'bson_ext'
gem 'domainatrix'
gem 'rack-test'
gem 'minitest'
gem 'thin'